"""
Django settings for jobPortal project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
# import ssl
# import certifi
# import truststore

# truststore.inject_into_ssl()

# CUSTOM_SSL_CONTEXT = ssl.create_default_context()
# CUSTOM_SSL_CONTEXT.load_verify_locations(certifi.where())

# EMAIL_SSL_CONTEXT = CUSTOM_SSL_CONTEXT

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ALLOWED_HOSTS = ['*']

SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", cast=bool)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'jobApp.apps.JobAppConfig',
    "storages",
    'django_ckeditor_5',
    'django_celery_results',
    'django_celery_beat',
    'widget_tweaks',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jobPortal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobPortal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

  
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.postgresql',

        'NAME': 'postgres',

        'USER': 'postgres',

        'PASSWORD': 'Klassnics@1759',

        'HOST': 'localhost',

        'PORT': '5432',

    }

}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
if DEBUG:
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
else:
    MEDIA_ROOT = r"C:\inetpub\wwwroot\jobPortal\media"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'jobApp.CustomUser'

SITE_ID = 1

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# ENVIRONMENT = config('ENVIRONMENT', default='local')

# if ENVIRONMENT == 'production':
#     # SENDGRID CONFIGURATION (for Render)
#     EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
#     SENDGRID_API_KEY = config('SENDGRID_API_KEY')
#     DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
# else:
#     # LOCAL SMTP CONFIGURATION (for your computer)
#     EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#     EMAIL_HOST = config("EMAIL_HOST")
#     EMAIL_PORT = config("EMAIL_PORT", cast=int)
#     EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
#     EMAIL_HOST_USER = config("EMAIL_HOST_USER")
#     EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
#     DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')


CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')

BASE_URL = 'https://readyremotejob.com'

GEMINI_API_KEY = config("GEMINI_API_KEY")

# USE_AZURE_STORAGE = config("USE_AZURE_STORAGE", default=not DEBUG, cast=bool)

# if USE_AZURE_STORAGE and not DEBUG:
#     # Azure Blob credentials
#     AZURE_ACCOUNT_NAME = config("AZURE_ACCOUNT_NAME")
#     AZURE_ACCOUNT_KEY = config("AZURE_ACCOUNT_KEY")
#     AZURE_CONNECTION_STRING = config("AZURE_CONNECTION_STRING")
#     AZURE_STATIC_CONTAINER = config("AZURE_STATIC_CONTAINER", default="staticfiles") # To rename later
#     AZURE_MEDIA_CONTAINER = config("AZURE_MEDIA_CONTAINER", default="mediafiles") # To rename later

#     STATIC_URL = f"https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_STATIC_CONTAINER}/"
#     MEDIA_URL = f"https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_MEDIA_CONTAINER}/"

#     STORAGES = {
#         "default": {
#             "BACKEND": "storages.backends.azure_storage.AzureStorage",
#             "OPTIONS": {
#                 "account_name": AZURE_ACCOUNT_NAME,
#                 "account_key": AZURE_ACCOUNT_KEY,
#                 "connection_string": AZURE_CONNECTION_STRING,
#                 "azure_container": AZURE_MEDIA_CONTAINER,
#             },
#         },
#         "staticfiles": {
#             "BACKEND": "storages.backends.azure_storage.AzureStorage",
#             "OPTIONS": {
#                 "account_name": AZURE_ACCOUNT_NAME,
#                 "account_key": AZURE_ACCOUNT_KEY,
#                 "connection_string": AZURE_CONNECTION_STRING,
#                 "azure_container": AZURE_STATIC_CONTAINER,
#             },
#         },
#     }

# AZURE_OVERWRITE_FILES = False

CSRF_TRUSTED_ORIGINS = [
     "https://readyremotejob.com"
]


# ---------------------------------------------------------
# CKEditor 5 Configuration
# ---------------------------------------------------------

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'link', 'bulletedList',
            'numberedList', 'blockQuote', 'codeBlock', '|',
            'imageUpload', 'fileUpload', 'mediaEmbed', 'undo', 'redo'
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative', '|',
                'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight'
            ],
            'styles': ['full', 'alignLeft', 'alignRight']
        },
        'theme': 'lark',
        'language': 'en',
        'file_storage_path': 'ckeditor5_uploads/',
        'media_embed': {'previewsInData': True},
    },
    'extends': {
        'block_toolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|', 'bulletedList', 'numberedList', '|', 'blockQuote'
        ],
        'toolbar': [
            'heading', '|', 'outdent', 'indent', '|', 'bold', 'italic',
            'link', 'underline', 'strike', 'subscript', 'superscript',
            'code', 'removeFormat', '|', 'bulletedList', 'numberedList',
            'todoList', '|', 'blockQuote', 'codeBlock', '|',
            'imageUpload', 'fileUpload', 'mediaEmbed', 'insertTable',
            'undo', 'redo'
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative', '|', 'imageStyle:alignLeft',
                'imageStyle:full', 'imageStyle:alignRight'
            ],
            'styles': ['full', 'alignLeft', 'alignRight']
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells',
                'tableProperties', 'tableCellProperties'
            ],
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'},
            ]
        },
        'file_storage_path': 'ckeditor5_uploads/',
        'media_embed': {'previewsInData': True},
    }
}

