# Generated by Django 5.2.4 on 2025-07-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0002_jobalert_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_expiry_date',
            field=models.DateTimeField(blank=True, help_text='Optional: Date when this job listing expires.', null=True),
        ),
    ]
