# Generated by Django 5.2.4 on 2025-08-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0005_alter_emailverificationtoken_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="The subscriber's email address.", max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-created_at'],
            },
        ),
    ]
