# Generated by Django 5.2.4 on 2025-09-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0007_blogcategory_post_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the blog post.', null=True, upload_to='blog_images/'),
        ),
    ]
