# Generated by Django 5.2.4 on 2025-09-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0009_remove_comment_is_approved_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
