# Generated by Django 5.2.4 on 2025-09-25 19:53

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0012_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
