# Generated by Django 5.2.4 on 2025-10-28 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0014_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, help_text="The user's primary resume file (PDF, DOCX).", null=True, upload_to='resumes/%Y/%m/')),
                ('resume_text', models.TextField(blank=True, help_text='Raw text extracted from the resume file (populated by a background task).')),
                ('parsed_skills', models.JSONField(blank=True, help_text="Skills extracted by the AI (e.g., ['Python', 'Django', 'React']).", null=True)),
                ('parsed_summary', models.TextField(blank=True, help_text="AI-generated summary of the applicant's profile.")),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
