# Generated by Django 5.2.4 on 2025-10-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0015_applicantprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='parsed_experience',
            field=models.JSONField(blank=True, help_text='Structured experience extracted by the AI.', null=True),
        ),
    ]
