# Generated by Django 5.2.4 on 2025-12-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0016_applicantprofile_parsed_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='email_address',
            field=models.EmailField(default='', help_text="Applicant's primary email address.", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(default='', help_text="Applicant's full name.", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='submitted_resume',
            field=models.FileField(blank=True, help_text="Applicant's submitted resume/CV file.", null=True, upload_to='job_applications/resumes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='job',
            name='application_method',
            field=models.CharField(choices=[('Internal', 'Internal Form Application'), ('External', 'External Link Application')], default='Internal', help_text='Choose the method applicants use to apply for this job.', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Application Submitted'), ('Clicked Apply Link', 'Clicked Apply Link'), ('Reviewed', 'Reviewed'), ('Interview', 'Interview Scheduled'), ('Rejected', 'Rejected'), ('Hired', 'Hired')], default='Clicked Apply Link', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='external_application_url',
            field=models.URLField(blank=True, help_text='External link for job application. Required if Application Method is External.', max_length=500, null=True),
        ),
    ]
