# Generated by Django 5.2.4 on 2025-12-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0017_application_address_application_email_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='availability_notice_period',
            field=models.CharField(blank=True, help_text="e.g., '2 weeks notice' or 'Immediate'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='expected_salary',
            field=models.CharField(blank=True, help_text="e.g., '€50,000'", max_length=255, null=True),
        ),
    ]
