# Generated by Django 5.2.4 on 2025-12-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0018_application_availability_notice_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='address',
        ),
    ]
