# Generated by Django 5.2.4 on 2026-01-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0021_jobsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsubscription',
            name='interest_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobsubscription',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
