# Generated by Django 5.2.4 on 2026-01-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0022_jobsubscription_interest_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsubscription',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
