# Generated by Django 5.2.4 on 2026-01-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0023_jobsubscription_is_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_method',
            field=models.CharField(choices=[('Internal', 'Internal Form Application'), ('External', 'External Link Application'), ('Email', 'Email/Description Only')], default='Internal', help_text='Choose the method applicants use to apply for this job.', max_length=50),
        ),
    ]
