# Generated by Django 5.2.4 on 2026-01-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0025_coursepurchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
