# Generated by Django 5.2.4 on 2026-01-10 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0027_ambassador'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsubscription',
            name='ambassador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_subscriptions', to='jobApp.ambassador'),
        ),
        migrations.AddField(
            model_name='jobsubscription',
            name='referral_code_used',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
