# Generated by Django 5.2.4 on 2026-01-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0028_jobsubscription_ambassador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='parsed_experience',
            field=models.JSONField(blank=True, help_text='Gaps or areas to highlight identified by AI.', null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='parsed_skills',
            field=models.JSONField(blank=True, help_text='Key strengths/matches identified by AI.', null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='parsed_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the fit.'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Temporary storage for resume file. Deleted immediately after text extraction.', null=True, upload_to='temp_resumes/'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='resume_text',
            field=models.TextField(blank=True, help_text='Temporary raw text for AI analysis. Deleted immediately after analysis completes.'),
        ),
    ]
