# Generated by Django 5.2.4 on 2026-01-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0029_alter_applicantprofile_parsed_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='resume_text',
        ),
    ]
