# Generated by Django 5.2.4 on 2026-01-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0030_remove_applicantprofile_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassador',
            name='account_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambassador',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambassador',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambassador',
            name='social_media_links',
            field=models.TextField(default='', help_text='Links to your profiles (Instagram, Twitter, etc.)'),
            preserve_default=False,
        ),
    ]
